#!/usr/bin/env bash
# This bash script transfers a file from our client to a server
if [ -z "$1" ]  || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/.
fi
