#!/usr/bin/env bash
# This script installs the nginx webserver on a server
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
