#!/usr/bin/env bash
# This script installs the nginx webserver on a server
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
