#!/usr/bin/env bash
# This script installs the nginx webserver on a server
#sudo apt-get -y install nginx
#echo "Hello World" | sudo tee $file > /dev/null
sudo sed -i '24 i \\trewrite ^/redirect_me$ http://chege.tech/ permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
