#!/usr/bin/env bash
# This bash script ensures nginx runs on TCP port 80.
sudo apt-get install -y nginx
sudo service nginx stop
sudo pkill nginx 
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo ufw allow 'Nginx HTTP'
