#!/usr/bin/env bash
# This bash script ensures nginx runs on TCP port 80.
sudo apt-get install -y nginx
sudo sed -i '/listen [0-9]/c \\tlisten 0.0.0.0:80 default_server;' /etc/nginx/sites-enabled/default
chown -R 755 /var/www
sudo pkill nginx 
sudo service nginx restart
sudo ufw allow 'Nginx HTTP'
