#!/usr/bin/env bash
# This bash script ensures nginx runs on TCP port 80.
ln -snf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
sed -i 's|pid /run/nginx/pid|pid /run/nginx_pid|' /etc/nginx/nginx.conf
