#!/usr/bin/env bash
# This bash script ensures nginx runs on TCP port 80.
sudo ln -snf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo sed -i 's|pid /run/nginx/pid|pid /run/nginx_pid|' /etc/nginx/nginx.conf
