#!/usr/bin/env bash
# Script displays "Best School" 10 times with a twist using while loop
i="1"
while [ $i -le 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
