#!/usr/bin/env bash
# This script gives you information about the school file
FILE=school
if test -f "$FILE"
then
	echo "$FILE file exists"
	if test -s "$FILE" && test -f "$FILE"
	then
		echo "$FILE is a regular file"
		echo "$FILE file is not empty"
	elif test -s "$FILE"
	then
		echo "$FILE file is empty"
	fi
else
	echo "$FILE file does not exist"
fi
