#!/usr/bin/env bash
# This script gives you information about the school file
FILE=school
if test -e "$FILE"
then
	echo "$FILE file exists"
	if test -f "$FILE"
	then
		echo "$FILE is a regular file"
	fi
	if test -s "$FILE"
	then
		echo "$FILE file is not empty"
	else
		echo "$FILE is empty"
	fi
else
	echo "$FILE file does not exist"
fi
