#!/usr/bin/env bash
# This script configures an ubuntu server with certain requirements
cp /etc/hosts /etc/hosts.bak
cp /etc/hosts /etc/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ /etc/hosts.new
echo "8.8.8.8    facebook.com" >> /etc/hosts.new
cp /etc/hosts.new /etc/hosts
