#!/usr/bin/env bash
# This script configures my web-server containers to run nginx as nginx user and to listen
# on all active-IPs on port 8080
sudo sed -i "s/listen 80 default_server/listen *:8080 default_server/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/#user/user nginx/g" /etc/nginx/nginx.conf
sudo service nginx restart
